// Generated by ../src/getcacheparms on aware.aladdin.cs.cmu.edu at Wed Oct 30 19:33:13 2019

#ifndef _CACHE_PARMS_H_
#define _CACHE_PARMS_H_
#define L1_Cache_Line_Size 64
#define L1_Log_Cache_Line_size 6
#endif
