#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include "util.h"

int verbose = 0;

void 
usage(void)
{
  fprintf(stderr, "%s: generate parameters for a system needed by hashtable code.\n", progname);
  fprintf(stderr, "\tExpectation is output is redirected to some .h file for inclusion\n");
  fprintf(stderr, "\tin building hashtable library\n");
  exit(-1);
}

typedef struct {
  int how;
  const char* fmt;
} Entry;

Entry output[] = {
  {1, "// Generated by %s on %s at %s"},
  {0, "#ifndef _CACHE_PARMS_H_"},
  {0, "#define _CACHE_PARMS_H_"},
  {2, "#define L1_Cache_Line_Size %d"},
  {3, "#define L1_Log_Cache_Line_size %d"},
  {0, "#endif"},
};

int
main(int argc, char** argv) 
{
  progname = argv[0];
  if (argc != 1) {
    usage();
  }

  int cls = getCacheLineSize();
  int lcls = log2Int(cls);

  char hostname[256];
  gethostname(hostname, 256);

  time_t rawtime;
  struct tm * timeinfo;

  time ( &rawtime );
  timeinfo = localtime ( &rawtime );
  const char* now = asctime (timeinfo);

  const int lines = sizeof(output) / sizeof(output[0]);
  FILE* out = stdout;

  for (int i=0; i<lines; i++) {
    switch (output[i].how) {
    case 0:
      fputs(output[i].fmt, out);
      break;
    case 1:
      fprintf(out, output[i].fmt, progname, hostname, now);
      break;
      
    case 2:
      fprintf(out, output[i].fmt, cls);
      break;

    case 3:
      fprintf(out, output[i].fmt, lcls);
      break;

    default:
      die("Unknown line %d to output, type %d", i, output[i].how);
    }
    fputc('\n', out);
  }
  return 0;
}
